### ISSUE TITLE
all blocked sites behind cloudflare die with 525

### ISSUE THREAD

**Issue by mssx86** [bol-van/zapret#70]
after fiddling with `nfqws` and `iptables` rules for an hour or so, i managed to pass the passive dpi that the government enforces on the monopolistic isp, turk telekom, here in turkey except for sites behind cloudflare. if the site is blocked and it is behind cloudflare, `4chan.org` and `pastebin.com` as examples, it automatically dies with a 525:
```sh
 0 ~: curl -I https://pastebin.com
HTTP/1.1 525 Origin SSL Handshake Error
Date: Sun, 09 May 2021 16:29:34 GMT
Content-Type: text/html
Content-Length: 207
Connection: keep-alive
Set-Cookie: __cfduid=d26d9ec82d97a5da9d0b7ed591cb920501620577774; expires=Tue, 08-Jun-21 16:29:34 GMT; path=/; domain=.pastebin.com; HttpOnly; SameSite=Lax; Secure
Cache-Control: no-store, no-cache
cf-request-id: 09f38f823900005075822bd000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 64cc4eb05bff5075-IST
```

i've found this quote from a cloudflare support ticket (it is a comment made by an user, not from an actual cloudflare employee so take it with a grain of salt):
>From Istanbul DC, their transit Turk Telekom filters edge traffic (which should never happen) and thus blocks access from edge to origins that should normally be the case only with local subscribers of ISPs. Cloudflare should do something about that.

anything i can try to get past this or am i out of luck because the cdn automatically picks the data center in istanbul due to latency?

here's the `iptables` rule i've set for `nfqws`:
```sh
iptables -t mangle -I POSTROUTING                                                \
  -p tcp -m multiport --dports 80,443                                            \
  -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 1:4 \
  -m mark ! --mark 0x40000000/0x40000000                                         \
  -j NFQUEUE --queue-num 200 --queue-bypass
```
and here's how i invoke `nfqws`:
```sh
nfqws --uid=0:0 \
     --qnum=200 --dpi-desync-fwmark=0x40000000 --wssize=1:6 \
     --hostcase --hostspell=hoST --hostnospace --domcase    \
     --dpi-desync=fake           \
     --dpi-desync-fooling=md5sig \
     --dpi-desync-retrans=1      \
     --dpi-desync-skip-nosni=0   \
     --dpi-desync-ttl=6 
```

**Comment by bol-van** [comment]
nfqws only works with the server _you_ are connecting to, it cannot influence further redirections made by the frontend
you get normal https response and it means nfqws did its job

**Comment by mssx86** [comment]
thank you a bunch, that was my initial thought as well. probably out of the scope of this issue but any idea how i can trick cloudflare to assign me a different node without getting rid of all of this with a vpn?

**Comment by bol-van** [comment]
I did traceroute to pastebin.com from 4 locations and in all cases last hops were different
pastebin.com resolves to the same 2 ipv4 addresses from any location and any DNS
this type of address is called AnyCast
104.23.99.190 belongs to many cloudflare servers worldwide. which one you are connecting to depends on your IP address
If cloudflare has a frontend in your country it means it makes outgoing connections to the backend from the same country and regulator restrictions apply.
Frontend acts as a proxy. dpi-desync only aplies to your connection, it cannot influence anything cloudflare does.
From the frontend answer its clear it attempts to make TLS connection to the backend and that's why any http modding (like --hostcase) tricks are also useless.
