### ISSUE TITLE
any viruses?

### ISSUE THREAD

**Issue by pupka-bit** [bol-van/zapret#832]
i just downloaded newest version and defender found virus called trojan wacatac
wth is this?

**Comment by bol-van** [comment]
It's AI heuristics. AV are known for false positives. They may not like windivert and upx

**Comment by IndeecFOX** [comment]
Т.к. утилита берёт ваши данные отправляемые в сеть, видоизменяет их чтобы dpi не обнаружили их, то естественно это внедрение в трафик и естественно об этом предупреждают. Ну как кухонный нож. Потенциально могут и в бочину зарядить))
Так же антивирусникам свойственно ругаться на различные программы активаторы, кейгены, кряки, и много чего ещё что вносит изменение в систему для обхода чего-либо, либо просто нарушает авторские права.

Since the utility takes your data sent to the network, modifies it so that dpi does not detect it, then naturally this is an injection into traffic and naturally they warn about it. Well, like a kitchen knife. Potentially they can charge you in the side))
Also, antiviruses tend to swear at various activator programs, keygens, cracks, and many other things that make changes to the system to bypass something, or simply violate copyright.

**Comment by Fenrir-0xFF** [comment]
> Т.к. утилита берёт ваши данные отправляемые в сеть, видоизменяет их чтобы dpi не обнаружили их

Больше удивляет что Zapret'ом иностранцы начяли пользоваться, думал такая хрень только в снг и китае

**Comment by IndeecFOX** [comment]
> Больше удивляет что Zapret'ом иностранцы начяли пользоваться, думал такая хрень только в снг и китае

Туркменистан жёстче. КНДР опять же. Иран тоже. Ещё кто-то был. Но и ничего не мешает тем же китайцам здесь писать. Или русскоязычным пользователям писать на английском тоже)

**Comment by Fenrir-0xFF** [comment]
> Туркменистан жёстче. КНДР опять же. Иран тоже. Ещё кто-то был. Но и ничего не мешает тем же китайцам здесь писать. Или русскоязычным пользователям писать на английском тоже)

Ну у китайцев там туева хучя всяких vpn они как правило ими пользуются, в КНДР скорей всего локальная сеть а не интернет, а для мартышек это вобще шайтанама технологии :-D
